sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      
    humidity:
      name: "Humidity"
    update_interval: ${sensor_update_interval}