# see https://esphome.io/components/wifi.html#

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # AP will have the devices same as the SSID name
  ap:
    password: !secret ap_password

captive_portal:


# WiFi diagnostics

# https://esphome.io/components/sensor/wifi_signal.html
# Example configuration entry with 2 sensors and filter
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

  - platform: uptime
    name: ${device_name} Uptime
    update_interval: 60s
    entity_category: "diagnostic"
    on_value:
        - mqtt.publish_json:
            topic: "${device_name}/sensors/uptime"
            payload: |-
              root["OutsideTemp"] = id(outside_temp).state;s/uptime"

# https://esphome.io/components/text_sensor/wifi_info.html
text_sensor:
  - platform: wifi_info
    ssid:
      name: Connected SSID
    ip_address:
      name: IP Address
    dns_address:
      name: DNS Address