sensor:
  - platform: lps22
    update_interval: ${sensor_update_interval}
    temperature:
      name: "LPS22 Temperature"
      id: lps22_temp
    pressure:
      name: "LPS22 Pressure"
      id: lps22_press
